/**
 * ExecutionPlan
 *
 * Responsibility:
 * ----------------
 * Represents the plan generated by the AI Planner.
 *
 * NOTE:
 * This is NOT an execution result.
 * It only describes WHAT should be executed.
 */
export interface ExecutionPlan {

    /**
     * High level goal.
     *
     * Example:
     * Execute Login Test
     */
    goal: string;

    /**
     * Plugin responsible for execution.
     *
     * Example:
     * web
     * salesforce
     * mobile
     */
    plugin: string;

    /**
     * Workflow name.
     *
     * Example:
     * Login
     * Account Creation
     */
    workflow: string;

    /**
     * Target application.
     *
     * Example:
     * Salesforce
     * SAP
     */
    application: string;

    /**
     * Country.
     *
     * Example:
     * Germany
     */
    country: string;

    /**
     * Environment.
     *
     * Example:
     * UAT
     * QA
     * PROD
     */
    environment: string;

}